### ISSUE TITLE
CSV file which is being read in the code

### ISSUE THREAD

**Issue by maheenmalik** [TestSmells/TestFileMapping#2]
Hello, can you please send the CSV file which you are reading in your main.java class?

**Comment by shehan** [comment]
The csv file contains only one column - the path to the unit test file.
A sample of this file is attached.
[detected_testfiles_sample.zip](https://github.com/TestSmells/TestFileMapping/files/2901807/detected_testfiles_sample.zip)

**Comment by maheenmalik** [comment]
Thank you so much for your assistance.
